FORMAT: 1A
HOST: http://api.knockrentals.com

# knock
Knock API is a service for vending and modifying data for knockrentals

# Group Authentication
Authenticating users through the **Knock API**

##Allowed HTTPs requests:

- `POST` - Creates or updates a resource
- `PUT` - Updates a resource
- `GET` - Retrieves a resource or list of resources
- `DELETE` - Delete a resource

# Group Calendar

## Confirmed Appointments [/api/v1/calendar/appointment?start={start}&end={end}]
### Get all confirmed appointments [GET]
+ Parameters
    + start (optional, date)
    + end (optional, date)
+ Response 200 (application/json)

        {
            "appointments": [
                {
                    "created_time": "Wed, 03 Sep 2014 08:29:23 GMT",
                    "end_time": "Mon, 09 Oct 2014 15:00:00 GMT",
                    "id": 2,
                    "is_active": true,
                    "manager_id": 1,
                    "manager_notes": null,
                    "modified_time": "Wed, 03 Sep 2014 08:29:23 GMT",
                    "renter_id": 2,
                    "renter_notes": "Some renter written writings",
                    "renter_visited": false,
                    "start_time": "Mon, 09 Sep 2014 15:00:00 GMT",
                    "status": "confirmed",
                    "type": "tour",
                    "listing": {
                       "id":"511 San Juan Circle, 99504",
                       "icon":"fa-home",
                       "address":"511 San Juan Circle, 99504",
                       "city":"Anchorage",
                       "state":"AK",
                       "price":1595,
                       "bedrooms":3,
                       "bathrooms":2,
                       "squareFeet":1100,
                       "available":null,
                       "pets":[
                    
                       ],
                       "geo":{
                          "longitude":-149.777217,
                          "latitude":61.217465
                       },
                       "images":[
                          "https://pa.cdn.appfolio.com/krkmanagement/images/30ba145a-b67b-4ce6-82f2-63c7d533d2fa/medium.jpg",
                          "https://pa.cdn.appfolio.com/krkmanagement/images/3ea08774-7de3-49d4-9d3d-686d7518eb30/medium.jpg",
                          "https://pa.cdn.appfolio.com/krkmanagement/images/9c8b6077-abbb-4358-8436-b57f5aebbfd4/medium.jpg",
                          "https://pa.cdn.appfolio.com/krkmanagement/images/45904a15-31fe-4b06-9f05-c46bb488ccd9/medium.jpg",
                          "https://pa.cdn.appfolio.com/krkmanagement/images/d19470de-efe5-4a07-812f-c8ae4ccbad6b/medium.jpg",
                          "https://pa.cdn.appfolio.com/krkmanagement/images/b392ac16-93d9-4a68-b64b-980b96cc87aa/medium.jpg",
                          "https://pa.cdn.appfolio.com/krkmanagement/images/e7d1ed55-3327-4611-89c5-1e22b7a4e18e/medium.jpg",
                          "https://pa.cdn.appfolio.com/krkmanagement/images/17247cb2-c7b4-428c-b6dd-1ed1a5a58a21/medium.jpg",
                          "https://pa.cdn.appfolio.com/krkmanagement/images/99908f90-c340-4782-8d19-273acf46593e/medium.jpg",
                          "https://pa.cdn.appfolio.com/krkmanagement/images/388236a7-d5fa-406a-8206-5365e1b3fc5c/medium.jpg",
                          "https://pa.cdn.appfolio.com/krkmanagement/images/89bd2c4c-d6ae-4ab2-9cf2-bbe1b7549885/medium.jpg",
                          "https://pa.cdn.appfolio.com/krkmanagement/images/367660f2-b03f-4965-93dd-5d9c7ebdeb24/medium.jpg",
                          "https://pa.cdn.appfolio.com/krkmanagement/images/21541216-9ce9-4dab-b30f-c7b9c1c1ea14/medium.jpg",
                          "https://pa.cdn.appfolio.com/krkmanagement/images/89ad8771-a5a3-437d-8008-3d1f7ce61e8b/medium.jpg",
                          "https://pa.cdn.appfolio.com/krkmanagement/images/aaa42e35-2772-480b-a0b3-b74ff522ecc4/medium.jpg"
                       ]
                    }
                },
                {
                    "created_time": "Wed, 03 Sep 2014 08:29:23 GMT",
                    "end_time": "Mon, 08 Sep 2014 17:15:00 GMT",
                    "id": 2,
                    "is_active": true,
                    "manager_id": 1,
                    "manager_notes": null,
                    "modified_time": "Wed, 03 Sep 2014 08:29:23 GMT",
                    "renter_id": 2,
                    "renter_notes": "Some renter written writings",
                    "renter_visited": false,
                    "start_time": "Mon, 08 Sep 2014 17:00:00 GMT",
                    "status": "confirmed",
                    "type": "tour",
                    "listing": {
                       "id":"511 San Juan Circle, 99504",
                       "icon":"fa-home",
                       "address":"511 San Juan Circle, 99504",
                       "city":"Anchorage",
                       "state":"AK",
                       "price":1595,
                       "bedrooms":3,
                       "bathrooms":2,
                       "squareFeet":1100,
                       "available":null,
                       "pets":[
                    
                       ],
                       "geo":{
                          "longitude":-149.777217,
                          "latitude":61.217465
                       },
                       "images":[
                          "https://pa.cdn.appfolio.com/krkmanagement/images/30ba145a-b67b-4ce6-82f2-63c7d533d2fa/medium.jpg",
                          "https://pa.cdn.appfolio.com/krkmanagement/images/3ea08774-7de3-49d4-9d3d-686d7518eb30/medium.jpg",
                          "https://pa.cdn.appfolio.com/krkmanagement/images/9c8b6077-abbb-4358-8436-b57f5aebbfd4/medium.jpg",
                          "https://pa.cdn.appfolio.com/krkmanagement/images/45904a15-31fe-4b06-9f05-c46bb488ccd9/medium.jpg",
                          "https://pa.cdn.appfolio.com/krkmanagement/images/d19470de-efe5-4a07-812f-c8ae4ccbad6b/medium.jpg",
                          "https://pa.cdn.appfolio.com/krkmanagement/images/b392ac16-93d9-4a68-b64b-980b96cc87aa/medium.jpg",
                          "https://pa.cdn.appfolio.com/krkmanagement/images/e7d1ed55-3327-4611-89c5-1e22b7a4e18e/medium.jpg",
                          "https://pa.cdn.appfolio.com/krkmanagement/images/17247cb2-c7b4-428c-b6dd-1ed1a5a58a21/medium.jpg",
                          "https://pa.cdn.appfolio.com/krkmanagement/images/99908f90-c340-4782-8d19-273acf46593e/medium.jpg",
                          "https://pa.cdn.appfolio.com/krkmanagement/images/388236a7-d5fa-406a-8206-5365e1b3fc5c/medium.jpg",
                          "https://pa.cdn.appfolio.com/krkmanagement/images/89bd2c4c-d6ae-4ab2-9cf2-bbe1b7549885/medium.jpg",
                          "https://pa.cdn.appfolio.com/krkmanagement/images/367660f2-b03f-4965-93dd-5d9c7ebdeb24/medium.jpg",
                          "https://pa.cdn.appfolio.com/krkmanagement/images/21541216-9ce9-4dab-b30f-c7b9c1c1ea14/medium.jpg",
                          "https://pa.cdn.appfolio.com/krkmanagement/images/89ad8771-a5a3-437d-8008-3d1f7ce61e8b/medium.jpg",
                          "https://pa.cdn.appfolio.com/krkmanagement/images/aaa42e35-2772-480b-a0b3-b74ff522ecc4/medium.jpg"
                       ]
                    }
                }
            ]
        }

## Appointment Request [/api/v1/calendar/request/]
### Get all appointment requests [GET]
+ Response 200 (application/json)

        {
            "requests": [
                {
                    "created_time": "Wed, 03 Sep 2014 08:29:23 GMT",
                    "end_time": "Mon, 13 Oct 2014 19:00:00 GMT",
                    "id": 2,
                    "is_active": true,
                    "listing_id": "9420d8f9202469a79df197455e9a595ff106f1cc",
                    "manager_id": 1,
                    "manager_notes": null,
                    "modified_time": "Wed, 03 Sep 2014 08:29:23 GMT",
                    "renter_id": 2,
                    "renter_notes": "Some renter written writings",
                    "renter_visited": false,
                    "start_time": "Mon, 13 Oct 2014 17:00:00 GMT",
                    "status": "pending",
                    "type": "tour"
                },
                {
                    "created_time": "Wed, 03 Sep 2014 08:29:28 GMT",
                    "end_time": "Mon, 13 Oct 2014 19:00:00 GMT",
                    "id": 3,
                    "is_active": true,
                    "listing_id": "9420d8f9202469a79df197455e9a595ff106f1cc",
                    "manager_id": 1,
                    "manager_notes": null,
                    "modified_time": "Wed, 03 Sep 2014 08:29:28 GMT",
                    "renter_id": 2,
                    "renter_notes": "Some renter written writings",
                    "renter_visited": false,
                    "start_time": "Mon, 13 Oct 2014 17:00:00 GMT",
                    "status": "pending",
                    "type": "tour"
                }
            ]
        }

### Create an appointment request [POST]
A request originating from a renter will replace the
given renter_id. The same is true for a request originating
from a manager (manager_id will be replaced).

+ Request (application/json)

        {
            "manager_id": 1,
            "renter_id": 2,
            "listing_id": "9420d8f9202469a79df197455e9a595ff106f1cc",
            "timezone": "US/Pacific",
            "start_time": "2014-10-13 10:00",
            "end_time": "2014-10-13 12:00",
            "type": "tour",
            "manager_notes": "A note from the manager" (optional),
            "renter_notes": "Some renter written writings" (optional)
        }

+ Response 201 (application/json)

        {
            "created": 4
        }



## Modify appointment request status [/api/v1/calendar/request/<request_id>/status]
Endpoints for a manager to accept or reject an appointment request

+ Parameters
    + request_id (required, number, `1`) ... Numeric `id` of the request to accept

### Change the status of an appointment request as a manager [POST]
+ Request (application/json)
    + Header

            Authorization: Bearer <manager-token>
    + Body

            {
                "status": "accepted" | "rejected"
            }

+ Response 201 (application/json)

        {
            "request_id": 4
        }



# Group Manager
## Manager [/api/v1/manager/]
### Get this manager [GET]
+ Request
    + Header

            Authorization: Bearer <manager-token>

+ Response 200 (application/json)

        {
            "manager": {
                "created_time": "Wed, 03 Sep 2014 06:41:48 GMT",
                "id": 1,
                "is_active": true,
                "modified_time": "Wed, 03 Sep 2014 06:41:48 GMT",
                "provider": "knock",
                "username": "daniel@knockrentals.com"
            }
        }

## Manager Info [/api/v1/manager/info]
### Get this manager's info [GET]
+ Request
    + Header

            Authorization: Bearer <manager-token>

+ Response 200 (application/json)

        {
            "manager_info": {
                "bio": "Doesn't like turtlenecks",
                "email": "fatisar@gmail.com",
                "first_name": "Daniel",
                "job_title": "Developer",
                "last_name": "Sarfati",
                "manager_id": 1,
                "phone": "210-216-6887",
                "photo": "steelydan.jpeg",
                "verification_method": "text"
            }
        }

### Update this manager's info [POST]
+ Request
    + Header

            Content-Type: application/json
            Authorization: Bearer <manager-token>

    + Body

            {
                "bio": "Doesn't like turtlenecks",
                "email": "fatisar@gmail.com",
                "first_name": "Daniel",
                "job_title": "Developer",
                "last_name": "Sarfati",
                "phone": "210-216-6887",
                "photo": "steelydan.jpeg",
                "verification_method": "text"
            }

+ Response 201 (application/json)
    + Body

            {
                "manager_info": 1
            }

## Manager Preferences [/api/v1/manager/preferences]
### Get this manager's preferences [GET]
+ Request
    + Header

            Authorization: Bearer <manager-token>

+ Response 200 (application/json)

        {
            "manager": {
                "adjacent_showing_interval": "0:15:00",
                "all_showings": false,
                "concurrent_showing_visitors": 3,
                "income_requirement_multiplier": 2,
                "manager_id": 1
            }
        }

### Update this manager's preferences [POST]
+ Request
    + Header

            Content-Type: application/json
            Authorization: Bearer <manager-token>
    + Body

            {
                "all_showings": false,
                "concurrent_showing_visitors": 3,
                "adjacent_showing_interval": 15,
                "income_requirement_multiplier": 1.5
            }
+ Response 201 (application/json)
    + Body

            {
                "manager_preferences": 1
            }

# Group Listing
## Listing [/v1/listing/<listing_id>]
### Get listing by id [GET]
+ Response 200 (application/json)
    + Body
    
            {
                "listing": {
                    "amenities": {
                        "appliances": null,
                        "common": [
                            "Air Conditioning",
                            "Alarm system",
                            "Built in Microwave",
                            "Cable ready",
                            "Cable-ready ",
                            "Ceiling Fans",
                            "Custom Cabinets",
                            "Dishwasher",
                            "Disposal",
                            "Electric Cooktop Stove",
                            "Side By Side Fridge",
                            "Tile floors",
                            "Walk-in Closet",
                            "Washer/Dryer In Unit",
                            "Window Coverings",
                            "www.rpmcentralar.com"
                        ],
                        "laundry": null,
                        "parking_type": "false",
                        "unit": [],
                        "utilities": {
                            "estimated_cost": null,
                            "included": []
                        },
                        "views": null
                    },
                    "basic": {
                        "bathrooms": 2,
                        "bedrooms": 2,
                        "price": 850,
                        "size": 1080
                    },
                    "debug": {
                        "raw_url": "https://webreq.propertyware.com/pw/marketing/website.do?sid=70287365&wid=69828613&uid=193200132&action=u",
                        "source": "propertyware",
                        "visibility": "internal"
                    },
                    "details": {
                        "description": {
                            "full": "*Real Property Management 501-834-1333 or www.rpmcentralar.com to apply* \rNew construction minutes from LRAFB. \r2br and 2 full bath, 1080sq ft. \r$50/mo discount for military members! \rFeatures include; Alarm system, Carport, Tile floors throughout, Fridge, Stove, DW, W, Walk-in Closet, and more. \rNo pets, No smoking inside",
                            "short": "113 W. Republican Rd., Jacksonville 72076"
                        },
                        "pets": {
                            "allowed": [
                                "any"
                            ],
                            "notes": ""
                        },
                        "smoking_allowed": "No",
                        "wheelchair_access": null
                    },
                    "id": "9da6ca9090582e8dbaf672b4eaf27b38b074bb11",
                    "leasing": {
                        "application": {
                            "fee": null,
                            "link": null
                        },
                        "available_date": "Fri, 01 Aug 2014 00:00:00 GMT",
                        "company": {
                            "name": "RPM Central Arkansas",
                            "phone": "",
                            "url": ""
                        },
                        "manager": {
                            "email": "rsherman501@gmail.com",
                            "imageID": "",
                            "name": "Robbie Sherman",
                            "phone": "(501) 834-1333"
                        },
                        "terms": {
                            "deposit": 800,
                            "lease_length": "12",
                            "lease_length_unit": "Months"
                        }
                    },
                    "location": {
                        "address": {
                            "city": "Jacksonville",
                            "house": "113",
                            "raw": "113 W. Republican Rd.  Jacksonville, AR, AR 72076",
                            "state": "AR",
                            "street": "W. Republican Rd.",
                            "unit": "",
                            "zip": "72076"
                        },
                        "geo": {
                            "coordinates": [
                                0,
                                0
                            ],
                            "type": "point"
                        },
                        "name": "113 W. Republican Rd., 72076",
                        "property_type": "Residential"
                    },
                    "photos": [
                        "http://s3.amazonaws.com/PRODBUCKET/95f2afa5-483b-414c-9a79-905b644e3cc4",
                        "http://s3.amazonaws.com/PRODBUCKET/cdd88d8a-f0d8-419c-8770-0681f8abb8ae",
                        "http://s3.amazonaws.com/PRODBUCKET/457740ec-ee89-45a3-80c5-b204a4abc8d2",
                        "http://s3.amazonaws.com/PRODBUCKET/f372d054-408d-4e3c-845e-390b4f8384cc",
                        "http://s3.amazonaws.com/PRODBUCKET/834b532c-41f7-4e3d-a502-c888471d9685",
                        "http://s3.amazonaws.com/PRODBUCKET/9abdf3e4-84d1-423d-92aa-11c0f0f005ee",
                        "http://s3.amazonaws.com/PRODBUCKET/5097f048-8ca9-4f64-93c3-d8305d3e55ea",
                        "http://s3.amazonaws.com/PRODBUCKET/f7c675f3-5d18-46e1-9ec8-301df6a539da",
                        "http://s3.amazonaws.com/PRODBUCKET/54b1d9bb-1003-47c5-9802-db9c0bfc53d7",
                        "http://s3.amazonaws.com/PRODBUCKET/83b48497-5bfe-4e7a-b0d2-5016ddac9b50"
                    ],
                    "promotions": null,
                    "social_urls": []
                },
                "num_results": 10,
                "page": 1,
                "total_pages": 1
            }

## Listing Calendar [/v1/listing/{listing_id}/calendar{?start,end}]

+ Parameters

    + listing_id (string) ... the ID of the listing
    + start (string) ... ISO-formatted datetime; "2014-09-01T00:00-07:00"
    + end (string) ... ISO-formatted datetime; "2014-09-07T23:59-07:00"
    
### Get this listing's calendar [GET]

+ Response 200 (application/json)
    
            {
                "appointments": [
                    {
                        "created_time": "Fri, 05 Sep 2014 18:51:25 GMT",
                        "end_time": "Fri, 05 Sep 2014 19:00:00 GMT",
                        "id": 8,
                        "is_active": true,
                        "listing_id": "9da6ca9090582e8dbaf672b4eaf27b38b074bb11",
                        "manager_id": 2,
                        "manager_notes": null,
                        "modified_time": "Fri, 05 Sep 2014 18:51:25 GMT",
                        "renter_id": 1,
                        "renter_notes": null,
                        "renter_visited": false,
                        "start_time": "Fri, 05 Sep 2014 18:00:00 GMT",
                        "status": "pending",
                        "type": "tour"
                    },
                    {
                        "created_time": "Sun, 07 Sep 2014 01:07:36 GMT",
                        "end_time": "Sat, 06 Sep 2014 17:00:00 GMT",
                        "id": 15,
                        "is_active": true,
                        "listing_id": "9da6ca9090582e8dbaf672b4eaf27b38b074bb11",
                        "manager_id": 2,
                        "manager_notes": null,
                        "modified_time": "Sun, 07 Sep 2014 01:07:36 GMT",
                        "renter_id": 1,
                        "renter_notes": "Some renter written writings",
                        "renter_visited": false,
                        "start_time": "Sat, 06 Sep 2014 16:00:00 GMT",
                        "status": "pending",
                        "type": "open_house"
                    }
                ],
                "open_houses": []
            }

## Listing Open House [/v1/listing/<listing_id>/openhouse/]
### Get all open houses at for this listing [GET]
+ Response 200 (application/json)

            [
                {
            
                }
            ]

